# Generated by Django 4.2.9 on 2024-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_weather', '0002_city_owm_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='owm_city_id',
            field=models.CharField(max_length=150, verbose_name='Id города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.CharField(max_length=150),
        ),
    ]
